name: Build and Push Docker image to Docker Hub

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx (Linux only)
        if: startsWith(matrix.operating-system, 'ubuntu')
        uses: docker/setup-buildx-action@v1

      - name: Set up Docker Buildx (Windows only)
        if: startsWith(matrix.operating-system, 'windows')
        run: |
          $buildxPath = "$env:USERPROFILE\buildx.exe"
          Invoke-WebRequest -Uri "https://github.com/docker/buildx/releases/download/v0.6.3/buildx-v0.6.3.windows-amd64.exe" -OutFile $buildxPath
          $env:Path = "$env:Path;$buildxPath"


      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .  # Use the root of the repository as the build context
          push: true
          tags: harshkr70/libraria_app:latest
